import { useEffect, useState } from "react";
import { API, Layout, formatDate } from "../components/Layout";

export default function Alerts(){const [stats,setStats]=useState({}),[scan,setScan]=useState({}),[alertText,setAlertText]=useState(""),[naukriText,setNaukriText]=useState(""),[message,setMessage]=useState("");
useEffect(()=>{Promise.all([fetch(`${API}/stats`),fetch(`${API}/scan/status`)]).then(async([a,b])=>{setStats(await a.json());setScan(await b.json())}).catch(()=>{})},[]);
async function importNaukri(){if(!naukriText.trim())return;try{const r=await fetch(`${API}/imports/naukri-alert`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:naukriText})});const d=await r.json();setMessage(r.ok?`${d.imported||0} Naukri alert jobs imported into the radar.`:(d.detail||"Import failed."));if(r.ok){setNaukriText("");setStats(await (await fetch(`${API}/stats`)).json())}}catch{setMessage("Could not reach the backend.")}}
async function importAlerts(){if(!alertText.trim())return;try{const r=await fetch(`${API}/imports/linkedin-alert`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:alertText})});const d=await r.json();setMessage(r.ok?`${d.imported||0} LinkedIn alert jobs imported into the radar.`:(d.detail||"Import failed."));if(r.ok){setAlertText("");setStats(await (await fetch(`${API}/stats`)).json())}}catch{setMessage("Could not reach the backend.")}}
return <Layout scanState={scan} onScan={async()=>{await fetch(`${API}/scan`,{method:"POST"});setMessage("Scan started in the background.")}}><section className="page"><div className="page-heading"><div><div className="eyebrow">NOTIFICATIONS & SOURCES</div><h1>Alerts & Job Sources</h1><p>Use permitted feeds and LinkedIn job-alert emails without authenticated LinkedIn scraping.</p></div></div>{message&&<div className="notice">{message}</div>}
<div className="alert-source-grid"><div className="panel source-card"><span className="source-icon">in</span><h2>LinkedIn Job Alert Import</h2><p>Paste the text from a LinkedIn job-alert email/notification. The radar extracts matching job titles and links and adds them to your normal scoring pipeline.</p><textarea className="alert-textarea" value={alertText} onChange={e=>setAlertText(e.target.value)} placeholder="Paste LinkedIn job alert text here…"/><button className="primary" onClick={importAlerts}>Import LinkedIn Alerts</button><small>No account credentials are requested or stored. Authenticated LinkedIn scraping is intentionally disabled.</small></div>
<div className="panel source-card"><span className="source-icon">N</span><h2>Naukri Job Alert Import</h2><p>Paste Naukri alert email/notification text. Matching roles enter the same scoring and tracking pipeline.</p><textarea className="alert-textarea" value={naukriText} onChange={e=>setNaukriText(e.target.value)} placeholder="Paste Naukri job alert text here…"/><button className="primary" onClick={importNaukri}>Import Naukri Alerts</button><small>No account credentials are requested or stored.</small></div>
<div className="panel source-card"><h2>Scanner health</h2><div className="source-health"><div><span>Career sites</span><b>Continuous</b></div><div><span>Greenhouse / Lever / RSS</span><b>Supported</b></div><div><span>LinkedIn</span><b>Alert import</b></div><div><span>Last scan</span><b>{scan.finished_at?formatDate(scan.finished_at):"Not yet completed"}</b></div><div><span>Collected last scan</span><b>{scan.last_result?.collected||0}</b></div><div><span>New last scan</span><b>{scan.last_result?.new||0}</b></div></div><a className="secondary button-link" href="/settings">Configure scanner →</a></div></div>
<div className="panel"><h2>Current source inventory</h2><div className="source-inventory"><div><b>{stats.companies||0}</b><span>Enabled companies</span></div><div><b>{Object.keys(stats.sources||{}).length}</b><span>Observed job sources</span></div><div><b>{stats.total||0}</b><span>Total active jobs</span></div><div><b>{stats.hyderabad||0}</b><span>Hyderabad jobs</span></div></div></div>
</section></Layout>}
